name: wurdinger_fnn_hyper.yaml
architecture:
    activation: relu
    input_dim: 2048
    output_dim: 1
    number_hidden_layers: 5
    number_hidden_neurons: 4096
regularization:
    input_dropout: 0.35
    dropout: 0.45