name: wurdinger_fnn_testset.yaml
architecture:
    activation: relu
    input_dim: 2048
    output_dim: 1
    number_hidden_layers: 4
    number_hidden_neurons: 2048
regularization:
    input_dropout: 0.35
    dropout: 0.45